<?php
// 2026-27 Upper Deck Tim Hortons Hockey checklist: [set_name, card_number, player_name]
// card_number is '' for unnumbered autograph/relic subjects
return [
    // Base
    ['Base', '1', 'Tim Horton'],
    ['Base', '2', 'Evan Bouchard'],
    ['Base', '3', 'Leo Carlson'],
    ['Base', '4', 'Miro Heiskanen'],
    ['Base', '5', 'Andrei Vasilevskiy'],
    ['Base', '6', 'Brock Boeser'],
    ['Base', '7', 'Brady Tkachuk'],
    ['Base', '8', 'Jordan Kyrou'],
    ['Base', '9', 'Jack Eichel'],
    ['Base', '10', 'Zach Werenski'],
    ['Base', '11', 'Travis Konecny'],
    ['Base', '12', 'Matt Boldy'],
    ['Base', '13', 'Sam Reinhart'],
    ['Base', '14', 'Nick Suzuki'],
    ['Base', '15', 'Jeremy Swayman'],
    ['Base', '16', 'Aleksander Barkov'],
    ['Base', '17', 'Dylan Strome'],
    ['Base', '18', 'Tim Stützle'],
    ['Base', '19', 'Matthew Tkachuk'],
    ['Base', '20', 'Sebastian Aho'],
    ['Base', '21', 'Aleksei Protas'],
    ['Base', '22', 'Drew Doughty'],
    ['Base', '23', 'Adam Fox'],
    ['Base', '24', 'Seth Jarvis'],
    ['Base', '25', 'Kevin Fiala'],
    ['Base', '26', 'Rasmus Dahlin'],
    ['Base', '27', 'Shea Theodore'],
    ['Base', '28', 'Jake Oettinger'],
    ['Base', '29', 'Nathan MacKinnon'],
    ['Base', '30', 'Ilya Sorokin'],
    ['Base', '31', 'Igor Shesterkin'],
    ['Base', '32', 'Dustin Wolf'],
    ['Base', '33', 'Ivan Demidov'],
    ['Base', '34', 'Auston Matthews'],
    ['Base', '35', 'Linus Ullmark'],
    ['Base', '36', 'Alex Tuch'],
    ['Base', '37', 'Connor Hellebuyck'],
    ['Base', '38', 'Jesper Bratt'],
    ['Base', '39', 'Matvei Michkov'],
    ['Base', '40', 'Elias Pettersson'],
    ['Base', '41', 'Lukas Raymond'],
    ['Base', '42', 'J.T. Miller'],
    ['Base', '43', 'Quinn Hughes'],
    ['Base', '44', 'Josh Morrissey'],
    ['Base', '45', 'Dylan Cozens'],
    ['Base', '46', 'Tyler Bertuzzi'],
    ['Base', '47', 'Darcy Kuemper'],
    ['Base', '48', 'Lane Hutson'],
    ['Base', '49', 'Patrick Kane'],
    ['Base', '50', 'Jordan Binnington'],
    ['Base', '51', 'William Eklund'],
    ['Base', '52', 'Juraj Slafkovsky'],
    ['Base', '53', 'Wyatt Johnston'],
    ['Base', '54', 'Matty Beniers'],
    ['Base', '55', 'Mark Scheifele'],
    ['Base', '56', 'Brayden Point'],
    ['Base', '57', 'Nico Hischier'],
    ['Base', '58', 'Kris Letang'],
    ['Base', '59', 'Roman Josi'],
    ['Base', '60', 'Moritz Seider'],
    ['Base', '61', 'Mark Stone'],
    ['Base', '62', 'Martin Necas'],
    ['Base', '63', 'Brad Marchand'],
    ['Base', '64', 'Owen Power'],
    ['Base', '65', 'Evgeni Malkin'],
    ['Base', '66', 'Logan Cooley'],
    ['Base', '67', 'Sean Monahan'],
    ['Base', '68', 'Jack Hughes'],
    ['Base', '69', 'Nikolai Ehlers'],
    ['Base', '70', 'Mathew Barzal'],
    ['Base', '71', 'Macklin Celebrini'],
    ['Base', '72', 'Tage Thompson'],
    ['Base', '73', 'Charlie McAvoy'],
    ['Base', '74', 'Jacob Slavin'],
    ['Base', '75', 'Tom Wilson'],
    ['Base', '76', 'Troy Terry'],
    ['Base', '77', 'Victor Hedman'],
    ['Base', '78', 'Trevor Zegras'],
    ['Base', '79', 'Kirill Kaprizov'],
    ['Base', '80', 'Sam Bennett'],
    ['Base', '81', 'Kyle Connor'],
    ['Base', '82', 'Frank Nazar'],
    ['Base', '83', 'Morgan Rielly'],
    ['Base', '84', 'Matthew Schaefer'],
    ['Base', '85', 'Will Smith'],
    ['Base', '86', 'Nikita Kucherov'],
    ['Base', '87', 'Sidney Crosby'],
    ['Base', '88', 'David Pastrnak'],
    ['Base', '89', 'Brandon Hagel'],
    ['Base', '90', 'Yegor Sharangovich'],
    ['Base', '91', 'Steven Stamkos'],
    ['Base', '92', 'Gabriel Landeskog'],
    ['Base', '93', 'Mitch Marner'],
    ['Base', '94', 'Brandon Montour'],
    ['Base', '95', 'Dylan Guenther'],
    ['Base', '96', 'Mikko Rantanen'],
    ['Base', '97', 'Connor McDavid'],
    ['Base', '98', 'Connor Bedard'],
    ['Base', '99', 'Clayton Keller'],
    ['Base', '100', 'Leon Draisaitl'],
    ['Base', '101', 'Cale Makar'],
    ['Base', '102', 'Robert Thomas'],
    ['Base', '103', 'Zach Hyman'],
    ['Base', '104', 'Nazem Kadri'],
    ['Base', '105', 'Bo Horvat'],
    ['Base', '106', 'Adam Fantilli'],
    ['Base', '107', 'Jared McCann'],
    ['Base', '108', 'Brock Faber'],
    ['Base', '109', 'Brayden Schenn'],
    ['Base', '110', 'Mason McTavish'],
    ['Base', '111', 'William Nylander'],
    ['Base', '112', 'J.J. Peterka'],
    ['Base', '113', 'Thatcher Demko'],
    ['Base', '114', 'Alex DeBrincat'],
    ['Base', '115', 'Filip Forsberg'],
    ['Base', '116', 'Logan Thompson'],
    ['Base', '117', 'Quinton Byfield'],
    ['Base', '118', 'Cole Caufield'],
    ['Base', '119', 'Dylan Larkin'],
    ['Base', '120', 'John Tavares'],
    // Above the Ice
    ['Above the Ice', 'AI-1', 'Dustin Wolf'],
    ['Above the Ice', 'AI-2', 'Leon Draisaitl'],
    ['Above the Ice', 'AI-3', 'Lane Hutson'],
    ['Above the Ice', 'AI-4', 'Brady Tkachuk'],
    ['Above the Ice', 'AI-5', 'William Nylander'],
    ['Above the Ice', 'AI-6', 'Quinn Hughes'],
    ['Above the Ice', 'AI-7', 'Connor Hellebuyck'],
    ['Above the Ice', 'AI-8', 'Matt Boldy'],
    ['Above the Ice', 'AI-9', 'Mathew Barzal'],
    ['Above the Ice', 'AI-10', 'Macklin Celebrini'],
    ['Above the Ice', 'AI-11', 'Zach Werenski'],
    ['Above the Ice', 'AI-12', 'Mitch Marner'],
    ['Above the Ice', 'AI-13', 'Tage Thompson'],
    ['Above the Ice', 'AI-14', 'Matthew Tkachuk'],
    ['Above the Ice', 'AI-15', 'Victor Hedman'],
    ['Above the Ice', 'AI-16', 'Aleksander Barkov'],
    ['Above the Ice', 'AI-17', 'Igor Shesterkin'],
    ['Above the Ice', 'AI-18', 'Filip Forsberg'],
    // Attack Angle
    ['Attack Angle', 'AA-1', 'Tim Stutzle'],
    ['Attack Angle', 'AA-2', 'David Pastrnak'],
    ['Attack Angle', 'AA-3', 'Jonathan Huberdeau'],
    ['Attack Angle', 'AA-4', 'Kirill Kaprizov'],
    ['Attack Angle', 'AA-5', 'Steven Stamkos'],
    ['Attack Angle', 'AA-6', 'Mark Scheifele'],
    ['Attack Angle', 'AA-7', 'Cole Caufield'],
    ['Attack Angle', 'AA-8', 'Jack Eichel'],
    ['Attack Angle', 'AA-9', 'Mikko Rantanen'],
    ['Attack Angle', 'AA-10', 'Jack Hughes'],
    ['Attack Angle', 'AA-11', 'Auston Matthews'],
    ['Attack Angle', 'AA-12', 'Nikita Kucherov'],
    ['Attack Angle', 'AA-13', 'Connor McDavid'],
    ['Attack Angle', 'AA-14', 'Elias Pettersson'],
    ['Attack Angle', 'AA-15', 'Matthew Tkachuk'],
    ['Attack Angle', 'AA-16', 'J.T. Miller'],
    ['Attack Angle', 'AA-17', 'Sidney Crosby'],
    ['Attack Angle', 'AA-18', 'Connor Bedard'],
    // First Liners
    ['First Liners', 'FL-1', 'Shea Theodore'],
    ['First Liners', 'FL-2', 'Leo Carlsson'],
    ['First Liners', 'FL-3', 'Mark Scheifele'],
    ['First Liners', 'FL-4', 'Travis Konecny'],
    ['First Liners', 'FL-5', 'Brayden Point'],
    ['First Liners', 'FL-6', 'Evan Bouchard'],
    ['First Liners', 'FL-7', 'Mathew Barzal'],
    ['First Liners', 'FL-8', 'Brady Tkachuk'],
    ['First Liners', 'FL-9', 'Robert Thomas'],
    ['First Liners', 'FL-10', 'David Pastrnak'],
    ['First Liners', 'FL-11', 'Drew Doughty'],
    ['First Liners', 'FL-12', 'Seth Jarvis'],
    ['First Liners', 'FL-13', 'Dylan Strome'],
    ['First Liners', 'FL-14', 'Josh Morrissey'],
    ['First Liners', 'FL-15', 'Jack Eichel'],
    ['First Liners', 'FL-16', 'Nick Suzuki'],
    ['First Liners', 'FL-17', 'Sidney Crosby'],
    ['First Liners', 'FL-18', 'Nathan MacKinnon'],
    // Next Gen Phenoms
    ['Next Gen Phenoms', 'NG-1', 'Connor Bedard'],
    ['Next Gen Phenoms', 'NG-2', 'Macklin Celebrini'],
    ['Next Gen Phenoms', 'NG-3', 'Matthew Schaefer'],
    ['Next Gen Phenoms', 'NG-4', 'Ivan Demidov'],
    ['Next Gen Phenoms', 'NG-5', 'Will Smith'],
    ['Next Gen Phenoms', 'NG-6', 'Beckett Senecke'],
    ['Next Gen Phenoms', 'NG-7', 'Michael Misa'],
    ['Next Gen Phenoms', 'NG-8', 'Ben Kindel'],
    ['Next Gen Phenoms', 'NG-9', 'Zeev Buium'],
    // Platinum Profiles
    ['Platinum Profiles', 'PP-1', 'Thatcher Demko'],
    ['Platinum Profiles', 'PP-2', 'Jordan Kyrou'],
    ['Platinum Profiles', 'PP-3', 'Brad Marchand'],
    ['Platinum Profiles', 'PP-4', 'Juraj Slafkovsky'],
    ['Platinum Profiles', 'PP-5', 'Dylan Larkin'],
    ['Platinum Profiles', 'PP-6', 'Quinton Byfield'],
    ['Platinum Profiles', 'PP-7', 'Matt Coronato'],
    ['Platinum Profiles', 'PP-8', 'Rasmus Dahlin'],
    ['Platinum Profiles', 'PP-9', 'Kirill Marchenko'],
    ['Platinum Profiles', 'PP-10', 'Anthony Stolarz'],
    ['Platinum Profiles', 'PP-11', 'Matthew Schaefer'],
    ['Platinum Profiles', 'PP-12', 'Miro Heiskanen'],
    ['Platinum Profiles', 'PP-13', 'Igor Shesterkin'],
    ['Platinum Profiles', 'PP-14', 'Kyle Connor'],
    ['Platinum Profiles', 'PP-15', 'Linus Ullmark'],
    ['Platinum Profiles', 'PP-16', 'Gabriel Landeskog'],
    ['Platinum Profiles', 'PP-17', 'Zach Hyman'],
    ['Platinum Profiles', 'PP-18', 'Sebastian Aho'],
    // Powerhouse Pillars
    ['Powerhouse Pillars', 'PO-1', 'Connor McDavid'],
    ['Powerhouse Pillars', 'PO-2', 'Sidney Crosby'],
    ['Powerhouse Pillars', 'PO-3', 'Nathan MacKinnon'],
    ['Powerhouse Pillars', 'PO-4', 'Nikita Kucherov'],
    ['Powerhouse Pillars', 'PO-5', 'Cale Makar'],
    ['Powerhouse Pillars', 'PO-6', 'Kirill Kaprizov'],
    // Sensational Cellys
    ['Sensational Cellys', 'SC-1', 'Lukas Dostal'],
    ['Sensational Cellys', 'SC-2', 'Erik Karlsson'],
    ['Sensational Cellys', 'SC-3', 'Matthew Knies'],
    ['Sensational Cellys', 'SC-4', 'Matt Coronato'],
    ['Sensational Cellys', 'SC-5', 'Logan Cooley'],
    ['Sensational Cellys', 'SC-6', 'Matvei Michkov'],
    ['Sensational Cellys', 'SC-7', 'Noah Dobson'],
    ['Sensational Cellys', 'SC-8', 'Adam Fox'],
    ['Sensational Cellys', 'SC-9', 'Jordan Binnington'],
    ['Sensational Cellys', 'SC-10', 'Gabe Villardi'],
    ['Sensational Cellys', 'SC-11', 'Jeremy Swayman'],
    ['Sensational Cellys', 'SC-12', 'Ilya Sorokin'],
    ['Sensational Cellys', 'SC-13', 'Lucas Raymond'],
    ['Sensational Cellys', 'SC-14', 'Jake Debrusk'],
    ['Sensational Cellys', 'SC-15', 'Carter Verhaeghe'],
    ['Sensational Cellys', 'SC-16', 'Drake Batherson'],
    ['Sensational Cellys', 'SC-17', 'Jesper Bratt'],
    ['Sensational Cellys', 'SC-18', 'Ryan Nugent-Hopkins'],
    // Sidekicks
    ['Sidekicks', 'SK-1', 'Nathan MacKinnon/Cale Makar'],
    ['Sidekicks', 'SK-2', 'Brad Marchand/Sam Bennett'],
    ['Sidekicks', 'SK-3', 'Brady Tkachuk/Tim Stutzle'],
    ['Sidekicks', 'SK-4', 'Auston Matthews/William Nylander'],
    ['Sidekicks', 'SK-5', 'Jack Eichel/Mitch Marner'],
    ['Sidekicks', 'SK-6', 'Connor McDavid/Leon Draisaitl'],
    ['Sidekicks', 'SK-7', 'Nikita Kucherov/Andrei Vasilevskiy'],
    ['Sidekicks', 'SK-8', 'Kyle Connor/Connor Hellebuyck'],
    ['Sidekicks', 'SK-9', 'Nick Suzuki/Cole Caufield'],
    // NHL Signatures
    ['NHL Signatures', '', 'Anthony Cirelli'],
    ['NHL Signatures', '', 'Anton Lundell'],
    ['NHL Signatures', '', 'Connor McDavid'],
    ['NHL Signatures', '', 'Dylan Guenther'],
    ['NHL Signatures', '', 'Dylan Samberg'],
    ['NHL Signatures', '', 'Dustin Wolf'],
    ['NHL Signatures', '', 'Filip Hronek'],
    ['NHL Signatures', '', 'Joey Daccord'],
    ['NHL Signatures', '', 'John Gibson'],
    ['NHL Signatures', '', 'Kent Johnson'],
    ['NHL Signatures', '', 'Matt Boldy'],
    ['NHL Signatures', '', 'Morgan Rielly'],
    ['NHL Signatures', '', 'Noah Dobson'],
    ['NHL Signatures', '', 'Ridly Greig'],
    ['NHL Signatures', '', 'Will Cuylle'],
    // Superstar Signatures
    ['Superstar Signatures', '/100', 'Nathan MacKinnon'],
    ['Superstar Signatures', '/87', 'Sidney Crosby'],
    // Timbits Autographs
    ['Timbits Autographs', '/100', 'Seth Jarvis'],
    // NHL Signature Jersey Relics
    ['NHL Signature Jersey Relics', '', 'Connor Hellebuyck'],
    ['NHL Signature Jersey Relics', '', 'Evan Bouchard'],
    ['NHL Signature Jersey Relics', '', 'Jake DeBrusk'],
    ['NHL Signature Jersey Relics', '', 'John Tavares'],
    ['NHL Signature Jersey Relics', '', 'Mikael Backlund'],
    ['NHL Signature Jersey Relics', '', 'Nick Suzuki'],
    // NHL Jersey Relics
    ['NHL Jersey Relics', '', 'Alex DeBrincat'],
    ['NHL Jersey Relics', '', 'Aaron Ekblad'],
    ['NHL Jersey Relics', '', 'Andrei Svechnikov'],
    ['NHL Jersey Relics', '', 'Brock Boeser'],
    ['NHL Jersey Relics', '', 'Brady Tkachuk'],
    ['NHL Jersey Relics', '', 'Connor Bedard'],
    ['NHL Jersey Relics', '', 'Cole Caufield'],
    ['NHL Jersey Relics', '', 'David Pastrnak'],
    ['NHL Jersey Relics', '', 'Gabe Vilardi'],
    ['NHL Jersey Relics', '', 'Jake Oettinger'],
    ['NHL Jersey Relics', '', 'Kirill Kaprizov'],
    ['NHL Jersey Relics', '', 'Leon Draisaitl'],
    ['NHL Jersey Relics', '', 'Logan Thompson'],
    ['NHL Jersey Relics', '', 'Rasmus Dahlin'],
    ['NHL Jersey Relics', '', 'Tomas Hertl'],
    ['NHL Jersey Relics', '', 'Vincent Trocheck'],
    ['NHL Jersey Relics', '', 'William Nylander'],
    ['NHL Jersey Relics', '', 'Yegor Sharangovich'],
];
