<?php
// 2025-26 Upper Deck Tim Hortons Hockey checklist: [set_name, card_number, player_name, bronzo_initial_qty]
return [
    ['Base Set', '1', 'Tim Horton', 1],
    ['Base Set', '2', 'Evan Bouchard', 0],
    ['Base Set', '3', 'Yegor Sharangovich', 2],
    ['Base Set', '4', 'Miro Heiskanen', 2],
    ['Base Set', '5', 'John Tavares', 1],
    ['Base Set', '6', 'Brock Boeser', 1],
    ['Base Set', '7', 'Brady Tkachuk', 1],
    ['Base Set', '8', 'Alex Ovechkin', 1],
    ['Base Set', '9', 'Filip Forsberg', 0],
    ['Base Set', '10', 'Artemi Panarin', 1],
    ['Base Set', '11', 'Anze Kopitar', 1],
    ['Base Set', '12', 'Matt Boldy', 1],
    ['Base Set', '13', 'Sam Reinhart', 2],
    ['Base Set', '14', 'Nick Suzuki', 2],
    ['Base Set', '15', 'Robert Thomas', 2],
    ['Base Set', '16', 'Mitch Marner', 1],
    ['Base Set', '17', 'William Karlsson', 1],
    ['Base Set', '18', 'Zach Hyman', 2],
    ['Base Set', '19', 'Matthew Tkachuk', 2],
    ['Base Set', '20', 'Juraj Slafkovsky', 2],
    ['Base Set', '21', 'Jason Robertson', 0],
    ['Base Set', '22', 'Cole Caufield', 1],
    ['Base Set', '23', 'Lucas Raymond', 1],
    ['Base Set', '24', 'Roope Hintz', 1],
    ['Base Set', '25', 'Jordan Kyrou', 0],
    ['Base Set', '26', 'Rasmus Dahlin', 1],
    ['Base Set', '27', 'William Eklund', 2],
    ['Base Set', '28', 'Claude Giroux', 1],
    ['Base Set', '29', 'Nathan MacKinnon', 2],
    ['Base Set', '30', 'Nazem Kadri', 1],
    ['Base Set', '31', 'Igor Shesterkin', 0],
    ['Base Set', '32', 'Adam Fox', 2],
    ['Base Set', '33', 'Jared McCann', 2],
    ['Base Set', '34', 'Auston Matthews', 1],
    ['Base Set', '35', 'Thatcher Demko', 1],
    ['Base Set', '36', 'Jesper Bratt', 1],
    ['Base Set', '37', 'Connor Hellebuyck', 2],
    ['Base Set', '38', 'Teuvo Teravainen', 1],
    ['Base Set', '39', 'Ryan Nugent-Hopkins-', 2],
    ['Base Set', '40', 'Elias Pettersson', 2],
    ['Base Set', '41', 'Patrik Laine', 1],
    ['Base Set', '42', 'Seth Jarvis', 1],
    ['Base Set', '43', 'Quinn Hughes', 1],
    ['Base Set', '44', 'Josh Morrissey', 1],
    ['Base Set', '45', 'Jonathan Huberdeau', 1],
    ['Base Set', '46', 'Jeremy Swayman', 1],
    ['Base Set', '47', 'John Carlson', 1],
    ['Base Set', '48', 'Dylan Guenther', 2],
    ['Base Set', '49', 'Tyler Bertuzzi', 1],
    ['Base Set', '50', 'J.T. Miller', 1],
    ['Base Set', '51', 'Mathew Barzal', 1],
    ['Base Set', '52', 'MacKenzie Weegar', 1],
    ['Base Set', '53', 'Logan Stankoven', 2],
    ['Base Set', '54', 'Tyler Toffoli', 1],
    ['Base Set', '55', 'Mark Scheifele', 1],
    ['Base Set', '56', 'Dylan Larkin', 1],
    ['Base Set', '57', 'Brock Nelson', 1],
    ['Base Set', '58', 'Leo Carlsson', 1],
    ['Base Set', '59', 'Roman Josi', 2],
    ['Base Set', '60', 'JJ Peterka', 1],
    ['Base Set', '61', 'Mark Stone', 1],
    ['Base Set', '62', 'Brandon Montour', 1],
    ['Base Set', '63', 'Brad Marchand', 0],
    ['Base Set', '64', 'Brent Burns', 2],
    ['Base Set', '65', 'Kris Letang', 1],
    ['Base Set', '66', 'Quiton Byfield', 2],
    ['Base Set', '67', 'David Pastrnak', 2],
    ['Base Set', '68', 'Jack Hughes', 2],
    ['Base Set', '69', 'Patrick Kane', 1],
    ['Base Set', '70', 'Mason McTavish', 2],
    ['Base Set', '71', 'Evgeni Malkin', 1],
    ['Base Set', '72', 'Tage Thompson', 1],
    ['Base Set', '73', 'Charlie McAvoy', 1],
    ['Base Set', '74', 'Owen Tippett', 1],
    ['Base Set', '75', 'Vincent Trocheck', 0],
    ['Base Set', '76', 'Anthony Stolarz', 1],
    ['Base Set', '77', 'Victor Hedman', 2],
    ['Base Set', '78', 'Zach Werenski', 1],
    ['Base Set', '79', 'Kirill Kaprizov', 2],
    ['Base Set', '80', 'Cale Makar', 1],
    ['Base Set', '81', 'Kyle Connor', 2],
    ['Base Set', '82', 'Kevin Fiala', 1],
    ['Base Set', '83', 'Bo Horvat', 2],
    ['Base Set', '84', 'Dougie Hamilton', 1],
    ['Base Set', '85', 'Jake Sanderson', 2],
    ['Base Set', '86', 'Nikita Kucherov', 1],
    ['Base Set', '87', 'Sidney Crosby', 1],
    ['Base Set', '88', 'Andrei Vasilevskiy', 1],
    ['Base Set', '89', 'Alex Tuch', 2],
    ['Base Set', '90', 'Clayton Keller', 0],
    ['Base Set', '91', 'Steven Stamkos', 2],
    ['Base Set', '92', 'Leon Draisaitl', 1],
    ['Base Set', '93', 'Alex DeBrincat', 1],
    ['Base Set', '94', 'Nikolaj Ehlers', 2],
    ['Base Set', '95', 'Jake Guentzel', 2],
    ['Base Set', '96', 'Mikko Rantanen', 0],
    ['Base Set', '97', 'Connor McDavid', 1],
    ['Base Set', '98', 'Connor Bedard', 1],
    ['Base Set', '99', 'Jack Eichel', 1],
    ['Base Set', '100', 'Jon Marchessault', 2],
    ['Base Set', '101', 'Pavel Buchnevich', 1],
    ['Base Set', '102', 'Carter Verhaeghe', 1],
    ['Base Set', '103', 'Nico Hischier', 2],
    ['Base Set', '104', 'Macklin Celebrini', 2],
    ['Base Set', '105', 'Mike Matheson', 1],
    ['Base Set', '106', 'Travis Sanheim', 2],
    ['Base Set', '107', 'Matty Beniers', 2],
    ['Base Set', '108', 'William Nylander', 1],
    ['Base Set', '109', 'Andrei Svechnikov', 1],
    ['Base Set', '110', 'Noah Dobson', 2],
    ['Base Set', '111', 'Travis Konecny', 1],
    ['Base Set', '112', 'Brayden Point', 1],
    ['Base Set', '113', 'Adam Fantilli', 1],
    ['Base Set', '114', 'Trevor Zegras', 1],
    ['Base Set', '115', 'Noah Hanifin', 2],
    ['Base Set', '116', 'Aleksander Barkov', 0],
    ['Base Set', '117', 'Dylan Strome', 1],
    ['Base Set', '118', 'Tim Stutzle', 1],
    ['Base Set', '119', 'Drake Batherson', 2],
    ['Base Set', '120', 'Sebastian Aho', 2],
    ['Powerhouse Pillars', 'CP-1', 'Connor McDavid', 0],
    ['Powerhouse Pillars', 'CP-2', 'Sidney Crosby', 0],
    ['Powerhouse Pillars', 'CP-3', 'Auston Matthews', 0],
    ['Powerhouse Pillars', 'CP-4', 'Alex Ovechkin', 0],
    ['Powerhouse Pillars', 'CP-5', 'Nathan MacKinnon', 0],
    ['Powerhouse Pillars', 'CP-6', 'Connor Bedard', 0],
    ['National Selections', 'NS1', 'Connor McDavid', 0],
    ['National Selections', 'NS2', 'Sidney Crosby', 1],
    ['National Selections', 'NS3', 'Aleksander Barkov', 0],
    ['National Selections', 'NS4', 'Nathan MacKinnon', 0],
    ['National Selections', 'NS5', 'Auston Matthews', 0],
    ['National Selections', 'NS6', 'Cale Makar', 1],
    ['National Selections', 'NS7', 'Victor Hedman', 0],
    ['National Selections', 'NS8', 'Brad Marchand', 0],
    ['National Selections', 'NS9', 'Sam Reinhart', 0],
    ['Co-Stars', 'CO-1', 'Makar/MacKinnon', 0],
    ['Co-Stars', 'CO-2', 'McDavid/Draisaitl', 0],
    ['Co-Stars', 'CO-3', 'B.Tkachuk/Stutzle', 0],
    ['Co-Stars', 'CO-4', 'Suzuki/Caufield', 0],
    ['Co-Stars', 'CO-5', 'Pastrnak/McAvoy', 0],
    ['Co-Stars', 'CO-6', 'Matthews/Nylander', 1],
    ['Co-Stars', 'CO-7', 'Pettersson/Hughes', 1],
    ['Co-Stars', 'CO-8', 'Scheifele/Connor', 0],
    ['Co-Stars', 'CO-9', 'M.Tkachuk/Barkov', 1],
    ['Attack Angle', 'AA-1', 'Nick Suzuki', 0],
    ['Attack Angle', 'AA-2', 'Kirill Kaprizov', 0],
    ['Attack Angle', 'AA-3', 'Matthew Tkachuk', 0],
    ['Attack Angle', 'AA-4', 'Nikita Kucherov', 1],
    ['Attack Angle', 'AA-5', 'Leon Draisaitl', 0],
    ['Attack Angle', 'AA-6', 'Travis Konecny', 0],
    ['Attack Angle', 'AA-7', 'Nazem Kadri', 0],
    ['Attack Angle', 'AA-8', 'Artemi Panarin', 0],
    ['Attack Angle', 'AA-9', 'Sebastian Aho', 0],
    ['Attack Angle', 'AA-10', 'Kyle Connor', 2],
    ['Attack Angle', 'AA-11', 'David Pastrnak', 0],
    ['Attack Angle', 'AA-12', 'Brock Boeser', 0],
    ['Attack Angle', 'AA-13', 'Mitch Marner', 1],
    ['Attack Angle', 'AA-14', 'Alex Ovechkin', 1],
    ['Attack Angle', 'AA-15', 'Tage Thompson', 0],
    ['Attack Angle', 'AA-16', 'Brady Tkachuk', 1],
    ['Attack Angle', 'AA-17', 'Mikko Rantanen', 0],
    ['Attack Angle', 'AA-18', 'Jason Robertson', 2],
    ['True North Heroes', 'TNH-1', 'Mark Stone', 2],
    ['True North Heroes', 'TNH-2', 'Bo Horvat', 2],
    ['True North Heroes', 'TNH-3', 'Cale Makar', 1],
    ['True North Heroes', 'TNH-4', 'Sam Reinhart', 2],
    ['True North Heroes', 'TNH-5', 'Nazem Kadri', 1],
    ['True North Heroes', 'TNH-6', 'Brayden Point', 1],
    ['True North Heroes', 'TNH-7', 'Travis Konecny', 2],
    ['True North Heroes', 'TNH-8', 'Connor McDavid', 1],
    ['True North Heroes', 'TNH-9', 'Nathan MacKinnon', 1],
    ['True North Heroes', 'TNH-10', 'Claude Giroux', 2],
    ['True North Heroes', 'TNH-11', 'Steven Stamkos', 1],
    ['True North Heroes', 'TNH-12', 'Mitch Marner', 1],
    ['True North Heroes', 'TNH-13', 'Robert Thomas', 1],
    ['True North Heroes', 'TNH-14', 'William Nylander', 2],
    ['True North Heroes', 'TNH-15', 'Mark Scheifele', 1],
    ['True North Heroes', 'TNH-16', 'Sidney Crosby', 2],
    ['True North Heroes', 'TNH-17', 'Connor Bedard', 2],
    ['True North Heroes', 'TNH-18', 'Brad Marchand', 2],
    ['Above the Ice', 'AI-1', 'Josh Morrissey', 0],
    ['Above the Ice', 'AI-2', 'Anders Lee', 2],
    ['Above the Ice', 'AI-3', 'Jared McCann', 2],
    ['Above the Ice', 'AI-4', 'Elias Pettersson', 0],
    ['Above the Ice', 'AI-5', 'Ryan Nugent-Hopkins-', 1],
    ['Above the Ice', 'AI-6', 'John Tavares', 0],
    ['Above the Ice', 'AI-7', 'Tim Stutzle', 1],
    ['Above the Ice', 'AI-8', 'Roope Hintz', 0],
    ['Above the Ice', 'AI-9', 'Adam Fox', 2],
    ['Above the Ice', 'AI-10', 'Cale Makar', 1],
    ['Above the Ice', 'AI-11', 'Evan Bouchard', 2],
    ['Above the Ice', 'AI-12', 'Juraj Slavkovsky', 0],
    ['Above the Ice', 'AI-13', 'Jordan Kyrou', 1],
    ['Above the Ice', 'AI-14', 'Matt Boldy', 2],
    ['Above the Ice', 'AI-15', 'Clayton Keller', 0],
    ['Above the Ice', 'AI-16', 'Martin Necas', 2],
    ['Above the Ice', 'AI-17', 'Mackenzie Weegar', 2],
    ['Above the Ice', 'AI-18', 'Jack Eichel', 0],
    ['Goalie Etchings', 'GE-1', 'Jacob Markstrom', 1],
    ['Goalie Etchings', 'GE-2', 'Jeremy Swayman', 0],
    ['Goalie Etchings', 'GE-3', 'Filip Gustavsson', 1],
    ['Goalie Etchings', 'GE-4', 'Andrei Vasilevskiy', 2],
    ['Goalie Etchings', 'GE-5', 'Linus Ullmark', 1],
    ['Goalie Etchings', 'GE-6', 'Sam Montembeault', 0],
    ['Goalie Etchings', 'GE-7', 'Logan Thompson', 0],
    ['Goalie Etchings', 'GE-8', 'Sergei Bobrovsky', 2],
    ['Goalie Etchings', 'GE-9', 'Igor Shesterkin', 0],
    ['Goalie Etchings', 'GE-10', 'Jake Oettinger', 0],
    ['Goalie Etchings', 'GE-11', 'Thatcher Demko', 1],
    ['Goalie Etchings', 'GE-12', 'Ilya Sorokin', 2],
    ['Goalie Etchings', 'GE-13', 'Jordan Binnington', 2],
    ['Goalie Etchings', 'GE-14', 'Connor Hellebuyck', 1],
    ['Goalie Etchings', 'GE-15', 'Juuse Saros', 2],
    ['Goalie Etchings', 'GE-16', 'Joseph Woll', 2],
    ['Goalie Etchings', 'GE-17', 'Stuart Skinner', 1],
    ['Goalie Etchings', 'GE-18', 'Adin Hill', 1],
    ['Monumental Moments', 'MM-1', 'Sam Montembeault', 2],
    ['Monumental Moments', 'MM-2', 'Roman Josi', 2],
    ['Monumental Moments', 'MM-3', 'Dylan Guenther', 2],
    ['Monumental Moments', 'MM-4', 'Rasmus Dahlin', 0],
    ['Monumental Moments', 'MM-5', 'Filip Gustavsson', 2],
    ['Monumental Moments', 'MM-6', 'Sidney Crosby', 2],
    ['Monumental Moments', 'MM-7', 'Macklin Celebrini', 2],
    ['Monumental Moments', 'MM-8', 'Andrei Vasilevskiy', 2],
    ['Monumental Moments', 'MM-9', 'Sergei Bobrovsky', 2],
    ['Monumental Moments', 'MM-10', 'Evgeni Malkin', 2],
    ['Monumental Moments', 'MM-11', 'Nico Hischier', 1],
    ['Monumental Moments', 'MM-12', 'Steven Stamkos', 2],
    ['Monumental Moments', 'MM-13', 'Jordan Binnington', 2],
    ['Monumental Moments', 'MM-14', 'Sebastian Aho', 0],
    ['Monumental Moments', 'MM-15', 'Jonathan Huberdeau', 2],
    ['Monumental Moments', 'MM-16', 'Anze Kopitar', 2],
    ['Monumental Moments', 'MM-17', 'Nikolaj Ehlers', 2],
    ['Monumental Moments', 'MM-18', 'Jacob Markstrom', 1],
];
